<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>True</UseWPF>
    <NuGetAuditMode>all</NuGetAuditMode>
    <ApplicationIcon>ICON\icon.ico</ApplicationIcon>
    <UseWindowsForms>False</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="ICON\icon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
    <PackageReference Include="MaterialDesignThemes.MahApps" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="_data\EliminationTargets.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="_data\EliminationWeapons.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="_data\FetchItems.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="_data\TradeItems.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    </ItemGroup>

  <Target Name="SetBuildDate" BeforeTargets="CoreCompile">
    <Exec Command="powershell -Command &quot;$date = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'; (Get-Content BuildInfo.cs) -replace '__BUILD_DATE__', $date | Set-Content BuildInfo.cs&quot;" />
  </Target>
  
</Project>
